/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_easemob_emssl_EMJniCurl */

#ifndef _Included_com_easemob_emssl_EMJniCurl
#define _Included_com_easemob_emssl_EMJniCurl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    init
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_init
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    unInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_unInit
  (JNIEnv *, jclass);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    addBasicHeader
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_addBasicHeader
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    addBasicURLParam
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_addBasicURLParam
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    setHost
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_setHost
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    setCertPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_setCertPath
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    setCookie
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_setCookie
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    setProxy
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_setProxy
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    get
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_get
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jobject, jobject, jobject);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    postFromData
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_postFromData
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jobject, jobject, jobject);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    postJson
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_postJson
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jobject, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    putJson
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_putJson
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jobject, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    delete
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_delete
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jobject, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    postFile
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_postFile
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jobject, jstring, jobject, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    download
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_easemob_emssl_EMJniCurl_download
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jobject, jobject, jobject, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    syncGet
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;)I
 */
JNIEXPORT jobject JNICALL Java_com_easemob_emssl_EMJniCurl_syncGet
  (JNIEnv *, jclass, jstring, jstring, jobject, jobject, jobject, jobject);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    syncPostJson
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;)I
 */
JNIEXPORT jobject JNICALL Java_com_easemob_emssl_EMJniCurl_syncPostJson
  (JNIEnv *, jclass, jstring, jstring, jobject, jobject, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    syncPutJson
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;)I
 */
JNIEXPORT jobject JNICALL Java_com_easemob_emssl_EMJniCurl_syncPutJson
  (JNIEnv *, jclass, jstring, jstring, jobject, jobject, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    syncDelete
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;)I
 */
JNIEXPORT jobject JNICALL Java_com_easemob_emssl_EMJniCurl_syncDelete
  (JNIEnv *, jclass, jstring, jstring, jobject, jobject, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    syncPostFile
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jobject JNICALL Java_com_easemob_emssl_EMJniCurl_syncPostFile
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jobject, jstring, jobject, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    syncDownload
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/util/List;Ljava/lang/String;)I
 */
JNIEXPORT jobject JNICALL Java_com_easemob_emssl_EMJniCurl_syncDownload
  (JNIEnv *, jclass, jstring, jint, jstring, jobject, jobject, jobject, jobject, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    sha256
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_easemob_emssl_EMJniCurl_sha256
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_easemob_emssl_EMJniCurl
 * Method:    aesCbc
 * Signature: ([BILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_easemob_emssl_EMJniCurl_aesCbc
  (JNIEnv *, jclass, jbyteArray, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
